---
language: node_js
node_js:
  # we recommend testing addons with the same minimum supported node version as Ember CLI
  # so that your addon works for all apps
  - '8'

sudo: false
dist: trusty

addons:
  chrome: stable

cache: yarn

env:
  global:
    # See https://git.io/vdao3 for details.
    - JOBS=1

jobs:
  fail_fast: true

  include:
    # runs linting and tests with current locked deps
    - stage: "Tests"
      name: "Tests"
      script:
        - yarn lint:hbs
        - yarn lint:js
        - yarn test
        - yarn test:node

    # run additional tests against LTS versions of Ember CLI,
    # latest stable release and current beta
    - stage: "Additional Tests"
      env: EMBER_CLI_VERSION=~3.4.0
    - env: EMBER_CLI_VERSION=~3.8.0
    - env: EMBER_CLI_VERSION=~3.12.0
    - env: EMBER_CLI_VERSION=latest
    - env: EMBER_CLI_VERSION=beta

script:
  - yarn add -D ember-cli@${EMBER_CLI_VERSION}
  - yarn test:node
